services:
  render:
    build:
      context: .
      dockerfile: Dockerfile
    image: revideo-app
    container_name: revideo-render
    volumes:
      - .:/app
      - /app/node_modules
      - ./output:/app/output
    shm_size: "2gb"

  ui:
    image: revideo-app
    container_name: revideo-ui
    init: true
    ports:
      - "9000:9000"
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
      - ./output:/app/output
    command: sh -c "npx serve template-videos -l 3001 --cors & npm start"
    shm_size: "2gb"